version: 2.1

orbs:
  go: circleci/go@1.11.0

jobs:
  build-and-test:
    executor:
      name: go/default
      tag: "1.18"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true

workflows:
  main:
    jobs:
      - build
